#!/bin/bash

directory=$(zenity --file-selection --directory --filename="$HOME" --title="Select a directory to save the files to" --save)
urllist_file=$(mktemp)
url_list=$(zenity --text-info --filename="$urllist_file" --editable)
echo "$url_list" > "$urllist_file"
cat "$urllist_file" | ./flickr -d "$directory" -
rm "$urllist_file"
